<a href="https://colab.research.google.com/github/kaarthikalagappan/ai_course_projects/blob/master/HW4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
class CustomException(Exception):
    pass

class Incompatible(Exception):
    def __init__(self, msg):
        # Error message is stored in msg
        self.msg = msg
debug=False

In [0]:
def conv2d(input_mat, kernel_mat):
    if debug:
        print("input matrix shape: " + str(input_mat.shape))
        print("input matrix: \n" + str(input_mat))
        print("kernel matrix shape: " + str(kernel_mat.shape))
        print("kernel matrix: \n" + str(kernel_mat))
    
    #Since convolution requires us to rotate the matrix 180 degrees
    kernel_mat = np.rot90(np.rot90(kernel_mat))

    if(input_mat.ndim <= 2):
        (height,width) = input_mat.shape
        channels = 1
    else:
        (height,width,channels) = input_mat.shape
    
    if(height != width):
        raise Incompatible("Input is not a square matrix")
    if(height < len(kernel_mat)):
        raise Incompatible("Kernel matrix is bigger than input matrix, the result would be empty")

    #if it's always going to be square matricies, can use either height or width
    output_size = height-len(kernel_mat)+1

    output_mat = np.zeros((output_size, output_size))
    for h in range(output_size):
        for w in range(output_size):
            # commented out since our depth is going to be only one
            # if channels > 1:
            #     for c in range(channels):
            #         multiplied = np.multiply(input_mat[h:h+len(kernel_mat), w:w+len(kernel_mat), c], kernel_mat)
            #         added = np.sum(multiplied)
            #         output_mat[h][w] = output_mat[h][w]+added
            # else:
            multiplied = np.multiply(input_mat[h:h+len(kernel_mat), w:w+len(kernel_mat)], kernel_mat)
            added = np.sum(multiplied)
            output_mat[h][w] = added
    if debug:
        print("\noutput matrix shape: " + str(output_mat.shape))
        print("resulting matrix after convolution: \n" + str(output_mat))
    return output_mat


## Testing it

In [67]:
input_mat = np.array([[1,1,1,0,0], [0,1,1,1,0], [0,0,1,1,1], [0,0,1,1,0], [0,1,1,0,0]])
# Common image kernels:
kernel_mat = np.array([[1,0,1], [0,1,0], [1,0,1]])
# kernel_mat = np.array([[-1,-1,-1], [-1,8,-1], [-1,-1,-1]])
# kernel_mat = np.array([[(1/9),(1/9),(1/9)],[(1/9),(1/9),(1/9)],[(1/9),(1/9),(1/9)]])
debug=True
output_mat = conv2d(input_mat, kernel_mat)

expected_output = signal.convolve2d(input_mat, kernel_mat, mode='valid')
if np.array_equal(expected_output, output_mat):
    print("\nCorrect Output")
else:
    print("\nIncorrect Output!")


input matrix shape: (5, 5)
input matrix: 
[[1 1 1 0 0]
 [0 1 1 1 0]
 [0 0 1 1 1]
 [0 0 1 1 0]
 [0 1 1 0 0]]
kernel matrix shape: (3, 3)
kernel matrix: 
[[1 0 1]
 [0 1 0]
 [1 0 1]]

output matrix shape: (3, 3)
resulting matrix after convolution: 
[[4. 3. 4.]
 [2. 4. 3.]
 [2. 3. 4.]]

Correct Output


In [68]:
input_mat = np.array([[1,1,1,0,0], [0,1,1,1,0], [0,0,1,1,1], [0,0,1,1,0], [0,1,1,0,0]])
kernel_mat = np.array([[1]])
debug=True
output_mat = conv2d(input_mat, kernel_mat)

expected_output = signal.convolve2d(input_mat, kernel_mat, mode='valid')
if np.array_equal(expected_output, output_mat):
    print("\nCorrect Output")
else:
    print("\nIncorrect Output!")


input matrix shape: (5, 5)
input matrix: 
[[1 1 1 0 0]
 [0 1 1 1 0]
 [0 0 1 1 1]
 [0 0 1 1 0]
 [0 1 1 0 0]]
kernel matrix shape: (1, 1)
kernel matrix: 
[[1]]

output matrix shape: (5, 5)
resulting matrix after convolution: 
[[1. 1. 1. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1.]
 [0. 0. 1. 1. 0.]
 [0. 1. 1. 0. 0.]]

Correct Output


In [69]:
input_mat = np.array([[1,2,3,4,0], [4,3,2,1,0], [9,8,7,6,0], [9,8,7,6,0], [5,4,6,7,0]])
kernel_mat = np.array([[0,0,0], [0,1,0], [0,0,0]])
debug=True
output_mat = conv2d(input_mat, kernel_mat)

expected_output = signal.convolve2d(input_mat, kernel_mat, mode='valid')
if np.array_equal(expected_output, output_mat):
    print("\nCorrect Output")
else:
    print("\nIncorrect Output!")


input matrix shape: (5, 5)
input matrix: 
[[1 2 3 4 0]
 [4 3 2 1 0]
 [9 8 7 6 0]
 [9 8 7 6 0]
 [5 4 6 7 0]]
kernel matrix shape: (3, 3)
kernel matrix: 
[[0 0 0]
 [0 1 0]
 [0 0 0]]

output matrix shape: (3, 3)
resulting matrix after convolution: 
[[3. 2. 1.]
 [8. 7. 6.]
 [8. 7. 6.]]

Correct Output


In [70]:
from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []
debug = False
# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])

for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
#   if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
#     output_mat = []
#   else:
#     output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")


[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!

[[4.]]
Correct output!



Incompatible: ignored