<a href="https://colab.research.google.com/github/kaarthikalagappan/ai_course_projects/blob/master/HW4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
class CustomException(Exception):
    pass

class Incompatible(Exception):
    def __init__(self, msg):
        # Error message is stored in msg
        self.msg = msg
debug = False

In [0]:
def maxpooling2d(input_mat, s):
    
    if debug:
        print("maxpool window: " + str(s))
        print("input matrix shape: " + str(input_mat.shape))
        print("input matrix: \n" + str(input_mat))

    if(input_mat.ndim <= 2):
        (height,width) = input_mat.shape
        channels = 1
    else:
        (height,width,channels) = input_mat.shape

    if(height != width):
        raise Incompatible("Input is not a square matrix")
    if(height < s):
        raise Incompatible("Maxpool window is bigger than input matrix")

    #if it's always going to be square matricies
    output_size = int(np.floor((min(height,width))/s))

    output_mat = np.zeros((output_size, output_size))
    for h in range(output_size):
        for w in range(output_size):
            if channels > 1:
                for c in range(channels):
                    max_value = input_mat[h*s:h*s+s, w*s:w*s+s, c].max()
                    output_mat[h][w] = output_mat[h][w]+max_value
            else:
                max_value = input_mat[h*s:h*s+s, w*s:w*s+s].max()
                output_mat[h][w] = max_value
    
    if debug:
        print("\noutput matrix shape: " + str(output_mat.shape))
        print(str(output_mat))
    return output_mat


## Testing it

In [28]:
input_mat = np.array([[1,1,1,0,0], [0,1,1,1,0], [0,0,1,1,1], [0,0,1,1,0], [0,1,1,0,0]])
debug = True
output_mat = maxpooling2d(input_mat, 4)


maxpool window: 4
input matrix shape: (5, 5)
input matrix: 
[[1 1 1 0 0]
 [0 1 1 1 0]
 [0 0 1 1 1]
 [0 0 1 1 0]
 [0 1 1 0 0]]

output matrix shape: (1, 1)
[[1.]]


In [29]:
input_mat = np.array([[1,1,1,0,0], [0,1,1,1,0], [0,0,1,1,1], [0,0,1,1,0], [0,1,1,0,0]])
debug = True
output_mat = maxpooling2d(input_mat, 2)


maxpool window: 2
input matrix shape: (5, 5)
input matrix: 
[[1 1 1 0 0]
 [0 1 1 1 0]
 [0 0 1 1 1]
 [0 0 1 1 0]
 [0 1 1 0 0]]

output matrix shape: (2, 2)
[[1. 1.]
 [0. 1.]]


In [30]:
input_mat = np.array([[1,2,3,4,0], [4,3,2,1,0], [9,8,7,6,0], [9,8,7,6,0], [5,4,6,7,0]])
debug = True
output_mat = maxpooling2d(input_mat, 2)


maxpool window: 2
input matrix shape: (5, 5)
input matrix: 
[[1 2 3 4 0]
 [4 3 2 1 0]
 [9 8 7 6 0]
 [9 8 7 6 0]
 [5 4 6 7 0]]

output matrix shape: (2, 2)
[[4. 4.]
 [9. 7.]]


In [31]:
input_mat = np.array([[1,2,3,4,0,1], [4,3,2,1,0,7], [9,8,7,6,0,5], [9,8,7,6,0,3], [5,4,6,7,0,1], [12,0,34,55,31,2]])
debug = True
output_mat = maxpooling2d(input_mat, 3)


maxpool window: 3
input matrix shape: (6, 6)
input matrix: 
[[ 1  2  3  4  0  1]
 [ 4  3  2  1  0  7]
 [ 9  8  7  6  0  5]
 [ 9  8  7  6  0  3]
 [ 5  4  6  7  0  1]
 [12  0 34 55 31  2]]

output matrix shape: (2, 2)
[[ 9.  7.]
 [34. 55.]]


### Test Cases from the TAs

In [32]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
debug = False
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

# Note: This test case is not a square matrix, so an error will be raised
input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
#   output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")


[[4. 2.]
 [2. 4.]]
Correct output!


Incompatible: ignored